name: tests

on: push

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.8
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install .[lint]
  #    - name: Lint
  #       run: |
  #         black ./ --check
  #         flake8

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [windows-latest]
        python-version: [3.7, 3.8]
        # exclude:
        #   - os: windows-latest
        #     python-version: 3.7

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Test
        run: |
          pytest
          echo "Exited with '$?'"
      - name: Coverage
        uses: codecov/codecov-action@v1

  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   if: contains(github.ref, 'tags')
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: "3.x"
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -U setuptools setuptools_scm wheel twine
  #     - name: Build and publish
  #       env:
  #         TWINE_USERNAME: __token__
  #         TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
  #       run: |
  #         git tag
  #         python setup.py sdist bdist_wheel
  #         twine upload dist/*
